# Generated by Django 2.1.5 on 2019-05-15 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('culprit_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culprit', to=settings.AUTH_USER_MODEL)),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witeness', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
