# Generated by Django 2.1.5 on 2019-05-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('sell_type', models.CharField(choices=[('Bid', 'Item for Bidding'), ('Fixed', 'Fixed Price Item')], max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
