# Generated by Django 2.1.5 on 2019-05-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='product_image',
            field=models.ImageField(default='default_product.jpg', upload_to='item_pics'),
        ),
    ]
