# Generated by Django 2.1.5 on 2019-05-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0002_sell_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='seller',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Seller Username:'),
        ),
    ]
