# Generated by Django 2.1.5 on 2019-05-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0003_sell_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='seller',
        ),
    ]
