# Generated by Django 2.1.5 on 2019-05-08 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0004_remove_sell_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
