# Generated by Django 2.1.5 on 2019-05-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0005_sell_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='product_image',
            field=models.ImageField(blank=True, default='default_product.jpg', null=True, upload_to='item_pics'),
        ),
    ]
