# Generated by Django 2.1.5 on 2019-05-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taboo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taboo',
            old_name='taboo_word',
            new_name='word',
        ),
    ]
