# Generated by Django 2.1.5 on 2019-05-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taboo', '0002_auto_20190507_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taboo',
            new_name='Taboos',
        ),
    ]
