# Generated by Django 2.1.5 on 2019-05-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouforms', '0002_auto_20190506_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouform',
            name='u_type',
            field=models.IntegerField(default=0, verbose_name='User_Type'),
        ),
    ]
