# Generated by Django 2.1.5 on 2019-05-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouforms', '0003_ouform_u_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouform',
            name='u_type',
        ),
    ]
