# Generated by Django 2.1.5 on 2019-05-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryform',
            name='email',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
