# Generated by Django 2.1.5 on 2019-05-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190501_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryform',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
