# Generated by Django 2.1.5 on 2019-05-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190502_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entryform',
            name='credit_card',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
